name: Deploy Cajá Website to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H srv1845.hstgr.io >> ~/.ssh/known_hosts
    
    - name: Deploy to Hostinger
      run: |
        # Upload main files
        scp -i ~/.ssh/id_rsa index.html u921347543@srv1845.hstgr.io:/home/u921347543/public_html/
        scp -i ~/.ssh/id_rsa style.css u921347543@srv1845.hstgr.io:/home/u921347543/public_html/
        scp -i ~/.ssh/id_rsa script.js u921347543@srv1845.hstgr.io:/home/u921347543/public_html/
        scp -i ~/.ssh/id_rsa contact.php u921347543@srv1845.hstgr.io:/home/u921347543/public_html/
        
        # Create and upload config
        ssh -i ~/.ssh/id_rsa u921347543@srv1845.hstgr.io "mkdir -p /home/u921347543/public_html/config"
        scp -i ~/.ssh/id_rsa config/database.php u921347543@srv1845.hstgr.io:/home/u921347543/public_html/config/
        
        # Create and upload admin
        ssh -i ~/.ssh/id_rsa u921347543@srv1845.hstgr.io "mkdir -p /home/u921347543/public_html/admin"
        scp -i ~/.ssh/id_rsa admin/*.php u921347543@srv1845.hstgr.io:/home/u921347543/public_html/admin/
        
        # Set permissions
        ssh -i ~/.ssh/id_rsa u921347543@srv1845.hstgr.io "
          cd /home/u921347543/public_html
          chmod 644 *.html *.css *.js *.php
          chmod 644 config/*.php admin/*.php
          chmod 755 config admin
        "
    
    - name: Verify deployment
      run: |
        echo "✅ Cajá website deployed successfully!"
        echo "🎨 Widget 'Ajuda?' with Cajá icon active"
        echo "🟡 Golden colors applied"
        echo "📊 Database connected: u921347543_sitecaja"